from flask import Flask, render_template
import handlers.index, handlers.request, handlers.payments, handlers.tasks, handlers.settings

app = Flask(__name__)
static = '/static'

@app.route('/create_request', methods=['POST'])
def create_request(): return handlers.index.create_request()
@app.route('/search_requests', methods=['GET'])
def search_requests(): return handlers.index.search_requests()
@app.route('/fetch_requests', methods=['GET'])
def fetch_requests(): return handlers.index.fetch_requests()
@app.route('/active_requests', methods=['GET'])
def active_requests(): return handlers.index.active_requests()
@app.route('/fetch_request', methods=['GET'])
def fetch_request(): return handlers.request.fetch_request()
@app.route('/update_request', methods=['POST'])
def update_request(): return handlers.request.update_request()
@app.route('/fetch_works', methods=['GET'])
def fetch_works(): return handlers.request.fetch_works()
@app.route('/remove_request', methods=['POST'])
def remove_request(): return handlers.request.remove_request()
@app.route('/restore_request', methods=['POST'])
def restore_request(): return handlers.request.restore_request()
@app.route('/delete_request', methods=['POST'])
def delete_request(): return handlers.request.delete_request()
@app.route('/fetch_payments', methods=['GET'])
def fetch_payments(): return handlers.index.fetch_payments()
@app.route('/cancel', methods=['POST'])
def cancel(): return handlers.payments.cancel()
@app.route('/cancel_payment', methods=['POST'])
def cancel_payment(): return handlers.payments.cancel_payment()
@app.route('/submit', methods=['POST'])
def submit(): return handlers.payments.submit()
@app.route('/submit_payment', methods=['POST'])
def submit_payment(): return handlers.payments.submit_payment()

@app.route('/create_task', methods=['POST'])
def create_task(): return handlers.tasks.create_task()
@app.route('/fetch_tasks', methods=['GET'])
def fetch_tasks(): return handlers.tasks.fetch_tasks()
@app.route('/update_task', methods=['POST'])
def update_task(): return handlers.tasks.update_task()
@app.route('/create_pair', methods=['POST'])
def create_pair(): return handlers.tasks.create_pair()
@app.route('/fetch_pairs', methods=['GET'])
def fetch_pairs(): return handlers.tasks.fetch_pairs()
@app.route('/update_pair', methods=['POST'])
def update_pair(): return handlers.tasks.update_pair()

@app.route('/pay_usd', methods=['POST'])
def pay_usd(): return handlers.settings.pay_usd()
@app.route('/customer_id', methods=['GET'])
def customer_id(): return handlers.settings.customer_id()
@app.route('/save_card', methods=['POST'])
def save_card(): return handlers.settings.save_card()
@app.route('/download_data', methods=['GET'])
def download_data(): return handlers.settings.download_data()
@app.route('/delete_account', methods=['POST'])
def delete_account(): return handlers.settings.delete_account()

@app.route('/')
def index(): return render_template('index.html', static=static)
@app.route('/request/<request_id>', methods=['GET'])
def request(request_id): return render_template('request.html', static=static)
@app.route('/search', methods=['GET'])
def search(): return render_template('search.html', static=static)
@app.route('/tasks')
def tasks(): return render_template('tasks.html', static=static)
@app.route('/pairs')
def pairs(): return render_template('pairs.html', static=static)
@app.route('/welcome')
def welcome(): return render_template('welcome.html', static=static)
@app.route('/guides')
def guides(): return render_template('guides.html', static=static)
@app.route('/settings')
def settings(): return render_template('settings.html', static=static)
@app.route('/trash')
def trash(): return render_template('trash.html', static=static)
@app.route('/payments')
def payments(): return render_template('payments.html', static=static)
@app.route('/data')
def data(): return render_template('data.html', static=static)
@app.route('/accounts')
def accounts(): return render_template('accounts.html', static=static)
@app.route('/affiliate')
def affiliate(): return render_template('affiliate.html', static=static)
@app.route('/contact')
def contact(): return render_template('contact.html', static=static)
@app.route('/terms')
def terms(): return render_template('terms.html', static=static)
@app.route('/privacy')
def privacy(): return render_template('privacy.html', static=static)
@app.errorhandler(404)
def page_not_found(e): return render_template('404.html', static=static), 404
@app.before_request
def maintenance():
    if False: return 'Sorry. The service is temporarily unavailable.', 503
if __name__ == '__main__': app.run(host='127.0.0.1', port=8080, debug=True)